### ISSUE TITLE
Memory leak for netCDF-4 createfile() calls, with netCDF 4.4.1.1, 4.5.0-rc1, that does not occur with 4.4.1.

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1071]
With 4.4.1.1 and 4.5.0-rc1, the address sanitizer reports a problem for netCDF-4 iotypes:

For netCDF-4 serial:
<pre>
Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fd453feae60 in malloc (/lib64/libasan.so.3+0xc6e60)
    #1 0x7fd450c6a825 in NC4_buildpropinfo (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xdd825)
    #2 0x7fd450c6a4be in NC4_put_propattr (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xdd4be)
    #3 0x7fd450c54256 in nc4_create_file (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xc7256)
    #4 0x7fd450c5442b in NC4_create (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xc742b)
    #5 0x7fd450bd53dc in NC_create (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0x483dc)
    #6 0x7fd450bd4a8d in nc__create (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0x47a8d)
    #7 0x7fd450bd4a46 in nc_create (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0x47a46)
    #8 0x42cd76 in PIOc_createfile_int /home/ed/pio1/ParallelIO/src/clib/pioc_support.c:1803
    #9 0x421ba0 in PIOc_createfile /home/ed/pio1/ParallelIO/src/clib/pio_file.c:132
    #10 0x46ec05 in create_file_handler /home/ed/pio1/ParallelIO/src/clib/pio_msg.c:188
    #11 0x4805fa in pio_msg_handler2 /home/ed/pio1/ParallelIO/src/clib/pio_msg.c:2581
    #12 0x43bc33 in PIOc_init_async /home/ed/pio1/ParallelIO/src/clib/pioc.c:1554
    #13 0x41cfbc in main /home/ed/pio1/ParallelIO/tests/cunit/test_intercomm2.c:330
    #14 0x7fd44f8a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).

</pre>
For netCDF-4 parallel:
<pre>
=================================================================
==18536==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fc32cb83e60 in malloc (/lib64/libasan.so.3+0xc6e60)
    #1 0x7fc329803825 in NC4_buildpropinfo (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xdd825)
    #2 0x7fc3298034be in NC4_put_propattr (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xdd4be)
    #3 0x7fc3297ed256 in nc4_create_file (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xc7256)
    #4 0x7fc3297ed42b in NC4_create (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0xc742b)
    #5 0x7fc32976e3dc in NC_create (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0x483dc)
    #6 0x7fc32976bdcc in nc_create_par (/usr/local/netcdf-c-4.4.1.1_mpich-3.2/lib/libnetcdf.so.11+0x45dcc)
    #7 0x42cbad in PIOc_createfile_int /home/ed/pio1/ParallelIO/src/clib/pioc_support.c:1793
    #8 0x421ba0 in PIOc_createfile /home/ed/pio1/ParallelIO/src/clib/pio_file.c:132
    #9 0x46ec05 in create_file_handler /home/ed/pio1/ParallelIO/src/clib/pio_msg.c:188
    #10 0x4805fa in pio_msg_handler2 /home/ed/pio1/ParallelIO/src/clib/pio_msg.c:2581
    #11 0x43bc33 in PIOc_init_async /home/ed/pio1/ParallelIO/src/clib/pioc.c:1554
    #12 0x41cfbc in main /home/ed/pio1/ParallelIO/tests/cunit/test_intercomm2.c:330
    #13 0x7fc328440400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).

</pre>

This may be a netCDF bug - I will notify the netCDF team after a little more investigation.

**Comment by edhartnett** [comment]
OK, this is due to a bug in netCDF which has already been fixed on their master branch.

For now I have switched to using a recent clone of their master as my development netCDF. I will keep this reasonably up to date.

(Almost) all memory problems have gone away between 4.4.1.1 and the current netCDF master.
