### ISSUE TITLE
MPAS hangs with sort issue 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1338]
From Carl Ponder: an MPAS-A hang, I see these stack traces from the two ranks:
#0  0x0000000000e01fe7 in pio_map_sort () at /gpfs/fs1/SHARE/Utils/PIO/2019-02-22/PGI-18.10_OpenMPI-3.1.3_NetCDF-F-4.4.4/distro/src/clib/pioc.c:371
#1  0x0000000000e024fc in PIOc_InitDecomp () at /gpfs/fs1/SHARE/Utils/PIO/2019-02-22/PGI-18.10_OpenMPI-3.1.3_NetCDF-F-4.4.4/distro/src/clib/pioc.c:545
#2  0x0000000000de15ec in pio_initdecomp_internal ()
    at /gpfs/fs1/SHARE/Utils/PIO/2019-02-22/PGI-18.10_OpenMPI-3.1.3_NetCDF-F-4.4.4/distro/src/flib/piolib_mod.F90:817
#3  0x0000000000de17b1 in pio_initdecomp_dof_i8 ()
    at /gpfs/fs1/SHARE/Utils/PIO/2019-02-22/PGI-18.10_OpenMPI-3.1.3_NetCDF-F-4.4.4/distro/src/flib/piolib_mod.F90:844
#4  0x0000000000584569 in mpas_io_set_var_indices () at framework/mpas_io.fppized.f90:1300
#5  0x00000000005b38e1 in mpas_streamaddfield_generic () at framework/mpas_io_streams.fppized.f90:2404
value has been optimized out

I used these components for the build & run

  1) use.own                         6) openmpi/3.1.3     11) netcdf-c/4.6.1
  2) PrgEnv/PGI+OpenMPI/2018-11-07   7) szip/2.1.1        12) netcdf-f/4.4.4
  3) cuda/10.0.130.0                 8) zlib/1.2.11       13) pio/2019-02-22
  4) pgi/18.10                       9) pnetcdf/1.10.0
  5) hwloc/1.11.11                  10) hdf5/1.10.4

I built the PIO with these settings
cmake -DDEFAULT_TEST_TIMEOUT=3600 -D PIO_ENABLE_TIMING=OFF -D NetCDF_C_LOGGING_ENABLED=0 -D CMAKE_VERBOSE_MAKEFILE=1 -D NetCDF_C_PATH=$NETCDF_C -D NetCDF_Fortran_PATH=$NETCDF_F -D PnetCDF_PATH=$PNETCDF -DCMAKE_INSTALL_PREFIX=$PIO $PIO/distro

**Comment by jedwards4b** [comment]
Fixed in pio 2.4.1
