### ISSUE TITLE
address sanitizer error on current master

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1677]
```
running test_darray_multivar3
=================================================================
=================================================================
==1396522==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7fff564e972c at pc 0x7f070896b480 bp 0x7fff564e7d50 sp 0x7fff564e74f8
=================================================================
==1396523==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffce1ec08ec at pc 0x7f8fc27d8480 bp 0x7ffce1ebef20 sp 0x7ffce1ebe6c8
=================================================================
==1396521==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffebca560ec at pc 0x7f132b72f480 bp 0x7ffebca54710 sp 0x7ffebca53eb8
==1396520==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffe1860d94c at pc 0x7fed96d8c480 bp 0x7ffe1860bf80 sp 0x7ffe1860b728
READ of size 24 at 0x7fff564e972c thread T0
READ of size 24 at 0x7ffebca560ec thread T0
READ of size 24 at 0x7ffce1ec08ec thread T0
READ of size 24 at 0x7ffe1860d94c thread T0
    #0 0x7f070896b47f  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x9b47f)
    #1 0x7f0708602e48 in MPIDI_CH3U_Buffer_copy (/usr/local/lib/libmpi.so.12+0x160e48)
    #2 0x7f070864c115 in MPIDI_Isend_self (/usr/local/lib/libmpi.so.12+0x1aa115)
    #3 0x7f0708642a1f in MPID_Isend (/usr/local/lib/libmpi.so.12+0x1a0a1f)
    #4 0x7f07085c6ff8 in MPIC_Isend (/usr/local/lib/libmpi.so.12+0x124ff8)
    #5 0x7f07085814ca in MPIR_Alltoallw_intra_scattered (/usr/local/lib/libmpi.so.12+0xdf4ca)
    #6 0x7f07084dc7a9 in MPIR_Alltoallw_intra_auto (/usr/local/lib/libmpi.so.12+0x3a7a9)
    #7 0x7f07084dc8c4 in MPIR_Alltoallw_impl (/usr/local/lib/libmpi.so.12+0x3a8c4)
    #8 0x7f07084dd2ee in PMPI_Alltoallw (/usr/local/lib/libmpi.so.12+0x3b2ee)
    #9 0x7f07088b5a8a in pio_swapm (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0xbda8a)
    #10 0x7f0708865f69 in rearrange_comp2io (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0x6df69)
    #11 0x7f070881460f in PIOc_write_darray_multi (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0x1c60f)
    #12 0x55b74f1523e9 in test_multivar_darray (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/tests/cunit/.libs/test_darray_multivar3+0x73e9)
    #13 0x55b74f152e18 in main (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/tests/cunit/.libs/test_darray_multivar3+0x7e18)
    #14 0x7f07082d70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #15 0x55b74f150e2d in _start (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/tests/cunit/.libs/test_darray_multivar3+0x5e2d)

Address 0x7fff564e972c is located in stack of thread T0 at offset 508 in frame
    #0 0x7f0708811e95 in PIOc_write_darray_multi (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0x19e95)

  This frame has 14 object(s):
    [32, 33) 'frame_present' (line 204)
    [48, 49) 'fillvalue_present' (line 205)
    [64, 68) 'fndims' (line 132)
    [80, 84) 'fndims2' (line 132)
    #0 0x7f8fc27d847f  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x9b47f)
    [96, 100) 'mpierr' (line 133)
    [112, 116) 'msg' (line 203)
    #1 0x7f8fc246fe48 in MPIDI_CH3U_Buffer_copy (/usr/local/lib/libmpi.so.12+0x160e48)
    [128, 132) 'flushtodisk_int' (line 206)
    #2 0x7f8fc24b9115 in MPIDI_Isend_self (/usr/local/lib/libmpi.so.12+0x1aa115)
    [144, 148) 'ncid' (line 123)
    [160, 164) 'ioid' (line 123)
    #3 0x7f8fc24afa1f in MPID_Isend (/usr/local/lib/libmpi.so.12+0x1a0a1f)
    [176, 180) 'nvars' (line 123)
    #4 0x7f8fc2433ff8 in MPIC_Isend (/usr/local/lib/libmpi.so.12+0x124ff8)
    [192, 200) 'file' (line 128)
    [224, 232) 'vdesc0' (line 131)
    #5 0x7f8fc23ee4ca in MPIR_Alltoallw_intra_scattered (/usr/local/lib/libmpi.so.12+0xdf4ca)
    [256, 264) 'vdesc' (line 168)
    #6 0x7f8fc23497a9 in MPIR_Alltoallw_intra_auto (/usr/local/lib/libmpi.so.12+0x3a7a9)
    #7 0x7f8fc23498c4 in MPIR_Alltoallw_impl (/usr/local/lib/libmpi.so.12+0x3a8c4)
    [288, 296) 'arraylen' (line 124) <== Memory access at offset 508 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
    #8 0x7f8fc234a2ee in PMPI_Alltoallw (/usr/local/lib/libmpi.so.12+0x3b2ee)
      (longjmp and C++ exceptions *are* supported)
    #9 0x7f8fc2722a8a in pio_swapm (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0xbda8a)
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x9b47f) 
    #10 0x7f8fc26d2f69 in rearrange_comp2io (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0x6df69)
    #11 0x7f8fc268160f in PIOc_write_darray_multi (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/src/clib/.libs/libpioc.so.1+0x1c60f)
    #12 0x558381f413e9 in test_multivar_darray (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/tests/cunit/.libs/test_darray_multivar3+0x73e9)
    #13 0x558381f41e18 in main (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/tests/cunit/.libs/test_darray_multivar3+0x7e18)
Shadow bytes around the buggy address:
  0x10006ac95290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006ac952a0: 00 00 00 00 00 00 f1 f1 f1 f1 01 f2 01 f2 04 f2
  0x10006ac952b0: 04 f2 04 f2 04 f2 04 f2 04 f2 04 f2 04 f2 00 f2
  0x10006ac952c0: f2 f2 00 f2 f2 f2 f8 f2 f2 f2 00 f3 f3 f3 00 00
  0x10006ac952d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10006ac952e0: ca ca ca ca 00[04]cb cb cb cb cb cb 00 00 00 00
  0x10006ac952f0: ca ca ca ca 00 04 cb cb cb cb cb cb 00 00 00 00
  0x10006ac95300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006ac95310: 00 00 00 00 00 00 f1 f1 f1 f1 04 f2 04 f2 00 00
  0x10006ac95320: 00 04 00 00 00 04 00 00 00 04 f2 f2 00 00 00 00
  0x10006ac95330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
    #14 0x7f8fc21440b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #15 0x558381f3fe2d in _start (/var/lib/jenkins/workspace/ejh_PIO_asan/pio-2.5.1-development/_build/sub/tests/cunit/.libs/test_darray_multivar3+0x5e2d)

```

**Comment by edwardhartnett** [comment]
OK, this is no longer occuring. I am looking into memory issues this week, but this apparently is no longer one of them. ;-)
