### ISSUE TITLE
pio_decomp_fillval fails on ANL workstation

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#179]
pio_decomp_fillval fails on ANL workstatation, riemann, with a 
segmentation fault for PNETCDF iotype.

PNETCDF version = 1.6.1
GCC = 5.1.0
MPICH = 3.2

**Comment by jayeshkrishna** [comment]
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7FBD9E488BC7
#1  0x7FBD9E487DC0
#2  0x7FBD9D2CB0AF
#3  0x7FBD9DC23301
#4  0x7FBD9DC2379F
#5  0x7FBD9DC23417
#6  0x7FBD9DC2379F
#7  0x7FBD9DC23417
#8  0x7FBD9DC2379F
#9  0x7FBD9DB46DF7
#10  0x7FBD9DB46FFD
#11  0x7FBD9DC55B53
#12  0x7FBD9DC3803F
#13  0x4FC9F9 in ncmpii_file_set_view
#14  0x4D3A8F in ncmpii_wait_getput at nonblocking.c:0
#15  0x4D490F in ncmpii_wait
#16  0x4D5294 in ncmpi_wait_all
#17  0x4F4A40 in ncmpii_getput_varn at varn.c:0
#18  0x4F5045 in ncmpi_get_varn_all
#19  0x4756A0 in pio_read_darray_nc
#20  0x4720A8 in PIOc_read_darray
#21  0x4506EA in __piodarray_MOD_read_darray_internal_int at piodarray.F90:0
#22  0x452F56 in __piodarray_MOD_read_darray_1d_int
#23  0x43D5D8 in nc_write_1d_explicit_fval_pio_int_integer___
#24  0x42705B in pio_tf_test_driver__
#25  0x43DC28 in MAIN__ at pio_decomp_fillval.F90:0
Segmentation fault (core dumped)

**Comment by jayeshkrishna** [comment]
I have a fix for this issue and will be pushing it soon

**Comment by jayeshkrishna** [comment]
The test runs successfully on compute001 (another ANL workstation).

**Comment by jayeshkrishna** [comment]
Could be related to failures seen in #142
