### ISSUE TITLE
memory leak in fortran test

### ISSUE THREAD

**Issue by edwardhartnett** [NCAR/ParallelIO#1825]
Building like this:

`autoreconf -i && CFLAGS='-g -Wall -fsanitize=address -fno-omit-frame-pointer' FCFLAGS=" -fsanitize=address -fno-omit-frame-pointer" FC=mpifort CC=mpicc CPPFLAGS="-I/usr/local/mpe-2.4.9b/include -I/usr/local/pnetcdf-1.12.1/include -I/usr/local/netcdf-c-4.8.0-development_hdf5-1.10.7_logging_mpich/include" LDFLAGS="-L/usr/local/pnetcdf-1.12.1/lib -L/usr/local/netcdf-c-4.8.0-development_hdf5-1.10.7_logging_mpich/lib -L/usr/local/mpe-2.4.9b/lib" ./configure --enable-fortran && make -j clean && make -j check
`

The fortran unit test fails. I suspect some MPI resources used in the test are not being freed.

```

=================================================================
==67166==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7fcdcf167bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fcdce0e3fe1 in MPIDI_VCRT_Create (/usr/local/lib/libmpi.so.12+0x1a5fe1)

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7fcdcf167bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fcdce09cae5 in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eae5)

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7fcdcf167bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fcdce09cb1a in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eb1a)

SUMMARY: AddressSanitizer: 96 byte(s) leaked in 6 allocation(s).

=================================================================
==67165==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f733db33bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f733caaffe1 in MPIDI_VCRT_Create (/usr/local/lib/libmpi.so.12+0x1a5fe1)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f733db33bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f733ca68b1a in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eb1a)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f733db33bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f733ca68ae5 in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eae5)

SUMMARY: AddressSanitizer: 48 byte(s) leaked in 3 allocation(s).

=================================================================
==67164==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7f46f46debc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f46f365afe1 in MPIDI_VCRT_Create (/usr/local/lib/libmpi.so.12+0x1a5fe1)

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7f46f46debc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f46f3613ae5 in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eae5)

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7f46f46debc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f46f3613b1a in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eb1a)

SUMMARY: AddressSanitizer: 96 byte(s) leaked in 6 allocation(s).

=================================================================
==67163==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7fe024550bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fe0234ccfe1 in MPIDI_VCRT_Create (/usr/local/lib/libmpi.so.12+0x1a5fe1)

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7fe024550bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fe023485b1a in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eb1a)

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7fe024550bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fe023485ae5 in MPIR_Find_local_and_external (/usr/local/lib/libmpi.so.12+0x15eae5)

SUMMARY: AddressSanitizer: 96 byte(s) leaked in 6 allocation(s).

```

**Comment by edwardhartnett** [comment]
Actually I was running into the problem in #1804 

When I build with netcdf-c-4.7.4, all Fortran tests pass the address sanitizer run! ;-)

I will add a github workflow with the address sanitizer build.
