### ISSUE TITLE
test_pioc failed on a build using SGI's MPI

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#640]
On CDash, test_pioc failed recently on build Linux-3.12.62-60.64.8-default-x86_64-Intel-16.0.3 (nwscla-laramie1):
http://my.cdash.org/testDetails.php?test=29836084&build=1132345

```
/* When called with other error messages, these functions should
 * return PIO_EIO. */
if (check_mpi(NULL, 100, __FILE__, __LINE__) != PIO_EIO)
    return ERR_WRONG;
if (check_mpi(NULL, 10000, __FILE__, __LINE__) != PIO_EIO)
    return ERR_WRONG;
```

It looks that the second call to check_mpi() signals SIGSEGV:
```
...
MPT: #4  0x00002aaaab99ebbb in slave_sig_handler (signo=11, 
MPT:     siginfo=<optimized out>, extra=<optimized out>) at sig.c:563
MPT: #5  <signal handler called>
MPT: #6  0x00002aaaab9344b2 in PMPI_Error_string (errorcode=9899, 
MPT:     string=0x7fffffffb468 "(undefined error code 100)", 
MPT:     resultlen=0x7fffffffb414) at error_class.c:195
MPT: #7  0x0000000000468cd4 in check_mpi ()
MPT: #8  0x000000000045cbb1 in check_strerror_netcdf (my_rank=0)
MPT:     at /picnic/u/home/katec/dashboard/src/tests/cunit/test_pioc.c:534
...
```
This build is using SGI's Message Passing Interface (MPI), a component of SGI's Message Passing Toolkit (MPT). Probably the error code 10000 for testing has some strange issues with SGI's MPI (works with MPICH), like errorcode=9899.

The above test code was added by PR #616 to fix issue #608 (test check_mpi2 with known and unknown error codes).

It would be better to use MPI macros (defined in mpi.h) for error codes, instead of hard-coded values like 100 or 10000. We can use MPI_ERR_OTHER to replace 100 and use MPI_ERR_UNKNOWN to replace 10000.
MPI_ERR_OTHER: Known error not in this list
MPI_ERR_UNKNOWN: Unknown error

This should also fix the SIGSEGV issue with SGI's MPT: it knows MPI_ERR_UNKNOWN from MPI standard, but it might not know a hard-coded value of 10000 that could cause SIGSEGV.

**Comment by dqwu** [comment]
When this issue is fixed, please make sure to test on build Linux-3.12.62-60.64.8-default-x86_64-Intel-16.0.3 (nwscla-laramie1) that is using SGI's MPI/MPT.
